# fly.toml app configuration file generated for search-rails-ic on 2023-06-02T12:03:47+07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "search-rails-ic"
primary_region = "hkg"
console_command = "/rails/bin/rails console"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0


[env]
  DEPLOYED_HOST = "rails-ic.fly.dev"
  RAILS_ENV = "production"
  MAILER_DEFAULT_HOST = "localhost"
  MAILER_DEFAULT_PORT = "3000"
  MAILER_SENDER = "Test <noreply@nimblehq.co>"
  AVAILABLE_LOCALES = "en"
  DEFAULT_LOCALE = "en"
  FALLBACK_LOCALES = "en"
