default: &default
  DB_NAME: "google_search_ruby"
  DB_HOST: "localhost"
  DB_PORT: "5432"
  DB_USERNAME: "postgres"
  DB_PASSWORD: "postgres"
  MAILER_DEFAULT_HOST: "localhost"
  MAILER_DEFAULT_PORT: "3000"
  MAILER_SENDER: "Test <noreplyrailsic@gmail.com>"
  AVAILABLE_LOCALES: "en"
  DEFAULT_LOCALE: "en"
  FALLBACK_LOCALES: "en"
  SMTP_PORT: 587
  SMTP_MAIL_SERVER: 'smtp.gmail.com'

development:
  <<: *default

test:
  <<: *default
  TEST_RETRY: "0"

# Set environment variables required in the initializers in order to precompile the assets.
# Because it initializes the app, so all variables need to exist in the Docker build stage (used in bin/docker-assets-precompile).
docker_build:
  <<: *default
  SECRET_KEY_BASE: dummy_secret_key_base
